#!/usr/bin/env ruby 
require 'DownloadClass'

# Checking through all arguments.

downl_mode = false
downl_path = Dir.pwd
regex = "(.*)"
url = String.new()

ARGV.each_with_index do |a, i|
	case a
	when '-D'
		downl_mode = true
	when '-t'
		downl_path = ARGV[i+1]
	when '-R'
		regex = ARGV[i+1]
	when '-U'
		url = ARGV[i+1]
	end
end

# Displays a message to STDOUT if no arguments or no url

if ARGV.empty? || url.empty? then 
	puts "#{$0} [[-D] [-t downloadpath]] [-R regexp] -U url"
	exit
end

if downl_mode == true then
	html = DownloadClass.new(url, downl_path)
	array = html.SearchImg(regex)
	
	html.DownloadArray(array)

else
	list = DownloadClass.new(url, downl_path)
	array = list.SearchImg(regex)

	array.each do |item|
		puts "#{item.to_s}"
	end
end
