 ##
# .bashrc
# -------
# 
# written by the hardworking, melancholic boy. enjoy

 ##
# Settings related to history

shopt -s histappend  # keep history in other shells if having multiple bash sessions

 ##
# GoLang

GOROOT=$HOME/go

 ##
# PATH

PATH=/home/medik/bin/anaconda3/bin:/opt/jdk8/bin:~/bin:$GOROOT/bin:$PATH

source ~/.aliases

 ##
# Prompt

PS1="[\u@\h \W $] "

 ##
# Unlimited bashhistory

HISTSIZE=-1
HISTFILESIZE=-1


 ##
# Editor

EDITOR="emacsclient -t"

 ##
# Disable CTRL+S

stty -ixon

 ##
# lsgrep

function lsgrep {
    ls -l | grep $1
}
