 ##
# .bashrc
# -------
# 
# written by the hardworking, melancholic boy. enjoy

 ##
# Settings related to history

shopt -s histappend  # keep history in other shells if having multiple bash sessions

HISTSIZE=100000000000 # makes the bash history BIG
HISTFILESIZE=1000000000000

 ##
# GoLang

GOROOT=$HOME/go

 ##
# PATH

PATH=/home/medik/bin/anaconda3/bin:/opt/jdk8/bin:~/bin:$GOROOT/bin:$PATH

source ~/.aliases
source ~/.git-completion.bash

 ##
# Prompt

PS1="[\u@\h \W $] "

 ##
# Unlimited bashhistory

HISTSIZE=-1
HISTFILESIZE=-1




